### ISSUE TITLE
Catch ctrl (or command) + W to close a tab

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/visualizer-on-tabs#1]
We could catch the event and close the corresponding tab and ask for saving if required

**Comment by targos** [comment]
I would do it only if the application is in full screen

**Comment by stropitek** [comment]
ctrl+w is reserved in chrome and cannot be intercepted
https://chromium.googlesource.com/chromium/src/+/abbfa3e92777e0b55429cac3c880f12237732385/chrome/browser/ui/browser_command_controller.cc#228

I'm in favor of closing this issue

**Comment by lpatiny** [comment]
I guess the only possibility to circumvent this is to use ... electron.
Actually this could be a way to install our software in a company that does not allow Chrome. We can say that it requires our custom electron application ;)
